name: thyroid-nodule-evaluation

services:
  - name: backend
    github:
      repo: Basartemiz/website_for_thyroid_classification
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: professional-xs
    routes:
      - path: /
    health_check:
      http_path: /api/health/
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        type: SECRET
        value: "EX_CHANGE_ME_GENERATE_A_NEW_SECRET_KEY"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "${APP_DOMAIN},.ondigitalocean.app"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://${APP_DOMAIN}"
      - key: OPENAI_API_KEY
        type: SECRET
        value: "EX_CHANGE_ME_YOUR_OPENAI_API_KEY"
      - key: OPENAI_MODEL
        value: "gpt-4o"
      - key: OPENAI_EMBEDDING_MODEL
        value: "text-embedding-3-small"
      - key: VECTORSTORE_DIR
        value: "/data/chroma"
      - key: INIT_VECTORSTORE
        value: "true"
      - key: GUNICORN_WORKERS
        value: "2"
      - key: GUNICORN_THREADS
        value: "4"
      - key: PORT
        value: "8000"

databases:
  - name: db
    engine: PG
    production: false
    cluster_name: thyroid-db
    db_name: thyroid_db
    db_user: thyroid_user
